### PR TITLE
Draft: switch to another rollup snowpack plugin

### PR DESCRIPTION
**Pull request by manuel3108**
Fixes: #10 

I was able to open the Datepicker-Demo with this locally without any problems. Seems to be working from what i can see.

### CODE REVIEW

**Comment by antony** [comment]
If you run a build, as if you were publishing to npm - does the component still work?

The demo locally doesn't bundle at all, which is why swapping out the plugin makes no difference :)

**Comment by manuel3108** [comment]
Ahh I get it, but then i have literally no idea which options i should provide to the rollup config.

**Comment by antony** [comment]
I've just made the rollup plugin public - seems easier!

Give it a go and see if it works now :)

**Comment by manuel3108** [comment]
Works fine now. Thanks!

**Pull request closed without merging**
